In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.impute import SimpleImputer

In [4]:
diabetes=pd.read_csv('C:/Users/shubham.chhetri/Desktop/MYPROJECT/Machine learning/Preparing data for ML/diabetes_process_complete.csv')

In [5]:
diabetes.head()

,Unnamed: 0,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,0,6.0,148.0,72.0,35.0,219.028414,33.6,0.627,50.0,1
1,1,1.0,85.0,66.0,29.0,70.341550,26.6,0.351,31.0,0
2,2,8.0,183.0,64.0,32.0,270.573172,23.3,0.672,32.0,1
3,3,1.0,89.0,66.0,23.0,94.000000,28.1,0.167,21.0,0
4,4,0.0,137.0,40.0,35.0,168.000000,43.1,2.288,33.0,1

In [9]:
diabetes_features=diabetes.drop(['Unnamed: 0','Outcome'],axis=1)
diabetes_label=diabetes[['Outcome']]

In [10]:
mask=np.random.randint(0,100,size=diabetes_features.shape).astype(np.bool)#random make it 0
mask=np.logical_not(mask)

In [11]:
diabetes_features[mask]=np.nan
diabetes_features.sample(15)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
91,4.0,123.0,80.0,15.0,176.000000,32.0,0.443,34.0
288,4.0,96.0,56.0,17.0,49.000000,20.8,0.340,26.0
370,3.0,173.0,82.0,48.0,NaN,38.4,2.137,25.0
345,8.0,126.0,88.0,36.0,108.000000,38.5,0.349,49.0
20,3.0,126.0,88.0,41.0,235.000000,39.3,0.704,27.0
56,7.0,187.0,68.0,39.0,304.000000,37.7,0.254,41.0
508,2.0,84.0,50.0,23.0,76.000000,30.4,0.968,21.0
618,9.0,112.0,82.0,24.0,124.815484,28.2,1.282,50.0
397,0.0,131.0,66.0,40.0,177.956322,34.3,0.196,22.0
736,0.0,126.0,86.0,27.0,120.000000,27.4,0.515,21.0
711,5.0,126.0,78.0,27.0,NaN,29.6,0.439,40.0
515,3.0,163.0,70.0,18.0,105.000000,31.6,NaN,28.0
658,11.0,127.0,106.0,32.0,161.258540,39.0,0.190,51.0
427,1.0,181.0,64.0,30.0,180.000000,34.1,0.328,38.0
520,2.0,68.0,70.0,32.0,66.000000,25.0,0.187,25.0

In [12]:
from sklearn.pipeline import make_pipeline
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [13]:
x_train,x_test,y_train,y_test=train_test_split(diabetes_features,diabetes_label,test_size=0.2)

In [16]:
transformer=ColumnTransformer(transformers=[('features',SimpleImputer(strategy='mean'),[0,1,2,3,4,5,6,7])])

In [17]:
clf=make_pipeline(transformer,DecisionTreeClassifier(max_depth=4))
clf=clf.fit(x_train,y_train)
clf.score(x_train,y_train)

0.8143322475570033

In [18]:
y_pred=clf.predict(x_test)

In [20]:
from sklearn.metrics import accuracy_score

In [21]:
accuracy_score(y_pred,y_test)

0.7077922077922078